services:
  - type: web
    name: para-sports-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_SERVICE
        value: gmail
    healthCheckPath: /api/health
    autoDeploy: true
    preDeployCommand: npm run health-check
